imperial_city_beef/erp/urls.py
from django.urls import path

from . import views

app_name = 'erp'
urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<uuid:product_id>/', views.product_detail, name='product_detail'),
    path('cart/<uuid:customer_id>', views.cart, name='cart'),
    path('cart/checkout/<uuid:customer_id>', views.checkout, name='checkout'),
    path('logout/', views.logout_view, name='logout')

]

imperial_city_beef/imperial_city_beef/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('erp.urls')),
    path('', include('social_django.urls', namespace='social')),
    # path('logout/', logout,
    #   name='logout'),
]

imperial_city_beef/erp/models.py
from django.db import models
import uuid

class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    
    def __str__(self):
        return self.name

class InventoryMovement(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    count = models.IntegerField()

    def __str__(self):
        return f'{self.product} changed by {self.count} units.'

class Customer(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    shipping_address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=12)

    def __str__(self):
        return f'{self.name}'        

class SalesOrder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created_date = models.DateTimeField()

    def __str__(self):
        return f'Sales Order: {self.id}'     

class SalesOrderDetail(models.Model):
    sales_order = models.ForeignKey(SalesOrder, on_delete=models.CASCADE)    
    product = models.ForeignKey(Product, on_delete=models.CASCADE)   
    count = models.IntegerField()

    def __str__(self):
        return f'Sales Order Detail: {self.sales_order.id}' 

class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)   
    count = models.IntegerField()

    def __str__(self):
        return f"{self.count} {self.product}"

imperial_city_beef/erp/views.py
from django.contrib.auth import logout
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

from .models import Product, Cart

def index(request):
    context = {
        'user': request.user
    }
    return render(request, 'erp/index.html', context)

def products(request):
    products = Product.objects.all()    
    context = {'products': products}
    return render(request, 'erp/products.html', context)

def product_detail(request, product_id):
    try:
        product = get_object_or_404(Product, id=product_id)
        context = {'product': product}
        return render(request, 'erp/product_detail.html', context)
    except Product.DoesNotExist:
        raise Http404('Product does not exist')

def cart(request, customer_id):
    if request.user.is_authenticated:
        if request.method == 'GET':
            cart_items = Cart.objects.filter(customer_id=customer_id).select_related('product') 
            context = {
                'cart_items': cart_items,
                'customer_id': customer_id
                }
            return render(request, 'erp/cart.html', context) 

        if request.method == 'POST':
            product_id = request.environ['QUERY_STRING'].split('=')[1]
            product = Product.objects.get(id=product_id)

            cart_add = Cart(customer_id=customer_id, product_id=product_id, count=1)
            cart_add.save()

            products = Product.objects.all()    
            context = {
                'products': products,
                'product_added_to_cart': product.name
                }
            return render(request, 'erp/products.html', context)
    else:
        return render(request, 'erp/login.html')



def checkout(request, customer_id):
    Cart.objects.filter(customer_id=customer_id).delete()
    context = {}
    return render(request, 'erp/checkout.html', context)   

def logout_view(request):
    logout(request)    
    return render(request, 'erp/login.html')    


    

imperial_city_beef/erp/templates/erp/base.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Imperial City Beef</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/starter-template.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'erp:index' %}">Imperial City Beef</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'erp:products' %}">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'erp:cart' 'ab3cb7e8-12a8-4c9a-9c51-21e8925dd70f' %}">Cart</a>
      </li>
    </ul>
    {% if user %}
      <ul class="navbar-nav my-2 my-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'social:begin' 'google-oauth2' %}">
              Login
            </a>
            <a class="dropdown-item" href="{% url 'erp:logout' %}">Logout</a>
        </li>
      </ul>
    {% endif %}
  </div>
</nav>

<main role="main" class="container">

  <div class="starter-template">
    {% block content %}
    {% endblock %}
  </div>

</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"><\/script>')</script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script></body>
</html>

imperial_city_beef/erp/templates/erp/cart.html
{% extends 'erp/base.html' %}
{% block content %}
{% if cart_items %}
<form action="{% url 'erp:checkout' 'ab3cb7e8-12a8-4c9a-9c51-21e8925dd70f' %}" method="post">
    {% csrf_token %}
    <table class="table">
    <thead>
        <tr>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col"></th>
        </tr>
        </thead>
    <tbody>
        {% for item in cart_items %}  
            <tr>
            <td>{{item}}</td>
            <td>{{item.product.price}}</td>
            <td>1</td>
            <td><button type="button" class="btn btn-danger">X</button></td>
            </tr>           
        {% endfor %}
    </tbody>
    </table>
    <input class="btn btn-primary" type="submit" value="Checkout">
</form>
    {% else %}
        <div class="alert alert-warning" role="alert">
            Cart is empty
        </div>
    {% endif %}
{% endblock %}

imperial_city_beef/erp/templates/erp/checkout.html
{% extends 'erp/base.html' %}
{% block content %}
<div class="alert alert-success" role="alert">
    You have successfully checked out
</div>
{% endblock %}

imperial_city_beef/erp/templates/erp/index.html
{% extends 'erp/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/starter-template.css' %}">
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'images/hotdog1.jpg' %}" class="hotdog-carousel-img" alt="Chicago Hot Dog 1">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/hotdog2.jpg' %}" class="hotdog-carousel-img" alt="Chicago Hot Dog 2">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/hotdog3.jpg' %}" class="hotdog-carousel-img" alt="Chicago Hot Dog 3">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
{% endblock %}

imperial_city_beef/erp/templates/erp/login.html
{% extends 'erp/base.html' %} {% block content %}
<a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">
  Login
</a>
{% endblock %}

imperial_city_beef/erp/templates/erp/product_detail.html
{% extends 'erp/base.html' %}
{% block content %}
    {% if product %}
        <h1>{{ product.name }}</h1>
        <button type="button" class="btn btn-secondary">Add to Cart</button>
    {% else %}
        <p>No products are available.</p>
    {% endif %}
{% endblock %}

imperial_city_beef/erp/templates/erp/products.html
{% extends 'erp/base.html' %}
{% block content %}
    {% if product_added_to_cart %}
    <div class="alert alert-success" role="alert">
        {{product_added_to_cart}} added to cart
    </div>
    {% endif %}
    {% if products %}
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %} 
                <form action="{% url 'erp:cart' 'ab3cb7e8-12a8-4c9a-9c51-21e8925dd70f' %}?product_id={{product.id}}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}  
                    <tr>
                    <td>{{product}}</td>
                    <td>{{product.price}}</td>
                    <td><input id=123 class="btn btn-primary" type="submit" value="Add To Cart"></td>
                    </tr>  
                </form> 
                {% endfor %}
            </tbody>
        </table>
    
    {% else %}
    <p>No products are available.</p>
    {% endif %}
{% endblock %}